language: node_js
node_js:
  - '7.3'
  - '6.9'
  - '5.12'
  - '4.7'
services:
  - mysql
env:
  - MYSQL_HOST=127.0.0.1 MYSQL_PORT= MYSQL_USER=root MYSQL_PASSWORD= MYSQL_DB=creso_test
before_script:
  - mysql < schemas/creso_test.sql

script: npm run test-ci
